# Generated by Django 6.0 on 2026-01-25 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_doctorprofile_user_alter_labtechprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g., Hematology, Biochemistry', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range', models.CharField(help_text='e.g., 13.5-17.5 g/dL', max_length=255)),
                ('unit', models.CharField(help_text='e.g., g/dL, mg/dL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Sample Collected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('clinical_note', models.TextField(blank=True, help_text="Doctor's notes for the lab tech")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='users.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='users.patientprofile')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('technician_remarks', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lab_tech', models.ForeignKey(limit_choices_to={'role': 'LAB_TECH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.labrequest')),
            ],
        ),
    ]
