# Generated by Django 6.0 on 2026-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Sample Collected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('clinical_note', models.TextField(blank=True, help_text="Doctor's notes for the lab tech")),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('technician_remarks', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g., Hematology, Biochemistry', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range', models.CharField(help_text='e.g., 13.5-17.5 g/dL', max_length=255)),
                ('unit', models.CharField(help_text='e.g., g/dL, mg/dL', max_length=50)),
            ],
        ),
    ]
