# Generated by Django 6.0 on 2026-03-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_tech',
            field=models.ForeignKey(limit_choices_to={'role': 'LAB_TECH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.labrequest'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtestprofile'),
        ),
    ]
