# Generated by Django 6.0 on 2025-12-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_doctorprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
