# Generated by Django 6.0 on 2026-03-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.receptionistprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='clinical.appointment'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.receptionistprofile'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.appointment'),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='historicallabrequest',
            name='consultation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.consultation'),
        ),
        migrations.AddField(
            model_name='historicallabrequest',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='historicallabrequest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallabrequest',
            name='lab_tech',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.labtechprofile'),
        ),
        migrations.AddField(
            model_name='historicallabrequest',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='consultation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.consultation'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.pharmacistprofile'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='historicalvitals',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.appointment'),
        ),
        migrations.AddField(
            model_name='historicalvitals',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvitals',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='historicalvitals',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.nurseprofile'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='clinical.consultation'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='lab_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.labtechprofile'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='clinical.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pharmacistprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.prescription'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='clinical.appointment'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nurseprofile'),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='vitals',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical.vitals'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vitals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.vitals'),
        ),
    ]
