# Generated by Django 6.0 on 2025-12-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_consultation_historicalconsultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('COLLECTED', 'Sample Collected'), ('PENDING', 'Pending Results'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('COLLECTED', 'Sample Collected'), ('PENDING', 'Pending Results'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallabrequest',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=10),
        ),
    ]
