# Generated by Django 6.0 on 2026-01-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='recorder_level',
            new_name='reorder_level',
        ),
    ]
